### ISSUE TITLE
App crashed when I clicked any date on the calendar

### ISSUE THREAD

**Issue by darewealth** [SecUSo/privacy-friendly-food-tracker#54]
### Describe the bug.
When I clicked on any date on the calendar, the app crashed

### Screen recording.

https://youtu.be/uEmO53goVsM

### Devices and Versions)
* Device: [Gionee, X1]

* Version [7.0]

* App version [1.0.1]

### Log
```07-07 09:07:28.842  8060  8060 E AndroidRuntime: FATAL EXCEPTION: main
07-07 09:07:28.842  8060  8060 E AndroidRuntime: Process: org.secuso.privacyfriendlyfoodtracker, PID: 8060
07-07 09:07:28.842  8060  8060 E AndroidRuntime: java.lang.RuntimeException: Unable to resume activity {org.secuso.privacyfriendlyfoodtracker/org.secuso.privacyfriendlyfoodtracker.activities.OverviewActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'org.secuso.privacyfriendlyfoodtracker.activities.adapter.DatabaseEntry[] org.secuso.privacyfriendlyfoodtracker.activities.adapter.DatabaseFacade.getEntriesForDay(java.util.Date)' on a null object reference
07-07 09:07:28.842  8060  8060 E AndroidRuntime: 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3104)
07-07 09:07:28.842  8060  8060 E AndroidRuntime: 	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3135)
07-07 09:07:28.842  8060  8060 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2482)
07-07 09:07:28.842  8060  8060 E AndroidRuntime: 	at android.app.ActivityThread.-wrap11(ActivityThread.java)
07-07 09:07:28.842  8060  8060 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1345)
07-07 09:07:28.842  8060  8060 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
07-07 09:07:28.842  8060  8060 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
07-07 09:07:28.842  8060  8060 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5452)
07-07 09:07:28.842  8060  8060 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-07 09:07:28.842  8060  8060 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:781)
07-07 09:07:28.842  8060  8060 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:671)
07-07 09:07:28.842  8060  8060 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'org.secuso.privacyfriendlyfoodtracker.activities.adapter.DatabaseEntry[] org.secuso.privacyfriendlyfoodtracker.activities.adapter.DatabaseFacade.getEntriesForDay(java.util.Date)' on a null object reference
07-07 09:07:28.842  8060  8060 E AndroidRuntime: 	at org.secuso.privacyfriendlyfoodtracker.activities.OverviewActivity.refreshTotalCalorieCounter(OverviewActivity.java:276)
07-07 09:07:28.842  8060  8060 E AndroidRuntime: 	at org.secuso.privacyfriendlyfoodtracker.activities.OverviewActivity.onResume(OverviewActivity.java:101)
07-07 09:07:28.842  8060  8060 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1261)
07-07 09:07:28.842  8060  8060 E AndroidRuntime: 	at android.app.Activity.performResume(Activity.java:6381)
07-07 09:07:28.842  8060  8060 E AndroidRuntime: 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3093)```

**Comment by DestyNova** [comment]
Same symptoms here, although I can't get a stack trace at the moment. I suspect it's because the "Generating passphrase" setup step never seems to complete, but can be skipped by tapping the checkmark button.
