### ISSUE TITLE
Crashes on OPO when selecting calendar date

### ISSUE THREAD

**Issue by matthiasbeyer** [SecUSo/privacy-friendly-food-tracker#65]
The title says it all.

**Comment by fazlerabbi37** [comment]
I can report the same on Xiaomi Note 4.

Step to reproduce:

- Open App
- Tap on a Date

Expected result: app should continue
Actual result: app crashes and goes back to menu

Device: Xiaomi Note 4
OS: MIUI Global 10.2

**Comment by 1Maxnet1** [comment]
I can report the same on the Samsung Galaxy S5 Mini.
Step to reproduce:

    Open App
    Tap on a Date

Expected result: the app should continue
Actual result: app crashes and goes back to the menu

Device: Samsung Galaxy S5 Mini
OS: LineageOS 16.0 Beta

**Comment by kronna** [comment]
Exactly the same, I see this is open since 21 October, too bad really wanted to try this app.

**Comment by petermayer** [comment]
Thanks for reporting everybody! The problem is that this seems to be an upstream bug in Android. We are waiting for a fix there.

**Comment by tagru** [comment]
Some additional information: When starting the app for the first time, it gets stuck after "generating key" and never reaches "create database". After this, it is the same behavior like describe by the others before.

Device: Xiaomi Redmi 3s
OS: MIUI 10 Global 9.3.28 Beta (Based on Android 6.0.1)

**Comment by bertrand-benoit** [comment]
Same for me, with my Samsung Galaxy S7 Edge.

This is the corresponding Debug logs:
```
01-17 15:01:42.105 8061 8061 E AndroidRuntime: Process: org.secuso.privacyfriendlyfoodtracker, PID: 8061
01-17 15:01:42.105 8061 8061 E AndroidRuntime: java.lang.RuntimeException: Unable to resume activity {org.secuso.privacyfriendlyfoodtracker/org.secuso.privacyfriendlyfoodtracker.activities.OverviewActivity}: java.lang.NullPointerException: Attempt to invoke virtual method ‘org.secuso.privacyfriendlyfoodtracker.activities.adapter.DatabaseEntry[] org.secuso.privacyfriendlyfoodtracker.activities.adapter.DatabaseFacade.getEntriesForDay(java.util.Date)’ on a null object reference
01-17 15:01:42.105 8061 8061 E AndroidRuntime: at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3454)
01-17 15:01:42.105 8061 8061 E AndroidRuntime: at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3494)
01-17 15:01:42.105 8061 8061 E AndroidRuntime: at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2757)
01-17 15:01:42.105 8061 8061 E AndroidRuntime: at android.app.ActivityThread.-wrap12(ActivityThread.java)
01-17 15:01:42.105 8061 8061 E AndroidRuntime: at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1496)
01-17 15:01:42.105 8061 8061 E AndroidRuntime: at android.os.Handler.dispatchMessage(Handler.java:102)
01-17 15:01:42.105 8061 8061 E AndroidRuntime: at android.os.Looper.loop(Looper.java:154)
01-17 15:01:42.105 8061 8061 E AndroidRuntime: at android.app.ActivityThread.main(ActivityThread.java:6186)
01-17 15:01:42.105 8061 8061 E AndroidRuntime: at java.lang.reflect.Method.invoke(Native Method)
01-17 15:01:42.105 8061 8061 E AndroidRuntime: at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
01-17 15:01:42.105 8061 8061 E AndroidRuntime: at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
01-17 15:01:42.105 8061 8061 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method ‘org.secuso.privacyfriendlyfoodtracker.activities.adapter.DatabaseEntry[] org.secuso.privacyfriendlyfoodtracker.activities.adapter.DatabaseFacade.getEntriesForDay(java.util.Date)’ on a null object reference
01-17 15:01:42.105 8061 8061 E AndroidRuntime: at org.secuso.privacyfriendlyfoodtracker.activities.OverviewActivity.refreshTotalCalorieCounter(OverviewActivity.java:276)
01-17 15:01:42.105 8061 8061 E AndroidRuntime: at org.secuso.privacyfriendlyfoodtracker.activities.OverviewActivity.onResume(OverviewActivity.java:101)
01-17 15:01:42.105 8061 8061 E AndroidRuntime: at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1270)
01-17 15:01:42.105 8061 8061 E AndroidRuntime: at android.app.Activity.performResume(Activity.java:6788)
01-17 15:01:42.105 8061 8061 E AndroidRuntime: at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3431)
01-17 15:01:42.105 8061 8061 E AndroidRuntime: … 10 more
01-17 15:01:42.107 3383 19979 W ActivityManager: Force finishing activity org.secuso.privacyfriendlyfoodtracker/.activities.OverviewActivity
01-17 15:01:42.112 3383 19979 W ActivityManager: Force finishing activity org.secuso.privacyfriendlyfoodtracker/.activities.MainActivity
```

**Comment by caligari87** [comment]
Commenting that I'm also getting this issue on Android 7. App sits forever on [Preparation] screen but shows a checkmark button. Clicking the checkmark button allows proceeding past the preparation screen to the app, but tapping on a calendar day crashes.
